SELECT TOP (1000) [Gender]
      ,[Age]
      ,[Academic_Pressure]
      ,[Study_Satisfaction]
      ,[Sleep_Duration]
      ,[Dietary_Habits]
      ,[Have_you_ever_had_suicidal_thoughts]
      ,[Study_Hours]
      ,[Financial_Stress]
      ,[Family_History_of_Mental_Illness]
      ,[Depression]
      ,[Age_group]
      ,[Index_Column]
  FROM [Tableau Project 1].[dbo].[Depression+Student+Dataset]
